name: DEVOPS FastAPI DEMO

on:
  push:
    branches: 
      - main
      - development

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: install dependencies
        run: 
          pip3 install -r requirements.txt
      
      - name: unittest
        run: 
          pytest test/test.py
      
      - name: docker build
        run: 
          docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-demo-fastapi:${{ github.sha }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: docker push
        run: 
          docker push ${{ secrets.DOCKER_USERNAME }}/devops-demo-fastapi:${{ github.sha }}
